### ISSUE TITLE
Unable to log in - no status 'submitted'

### ISSUE THREAD

**Issue by CameronRushton** [CameronRushton/Graduate-Admission-System#104]
'Submitted' isn't a valid option to populate the db with in data.sql.
![image](https://user-images.githubusercontent.com/32455969/77697161-b8803e80-6f84-11ea-8a86-8c7b9edcf0f0.png)

**Comment by LukeANewton** [comment]
is that another difference between h2 and postgres? the statuses should all be uppercase, but h2 didnt seem to care when I was adding that. It should be a quick fix
