### ISSUE TITLE
H2 database deleted on heroku dyno sleep

### ISSUE THREAD

**Issue by CameronRushton** [CameronRushton/Graduate-Admission-System#21]
Currently, our database is reset when the application goes into a sleep state in heroku. The professor mentioned using postgreSQL instead of an H2 database to solve this issue. [Instructions on how to set this up are provided here](https://culearn.carleton.ca/moodle/pluginfile.php/3671185/mod_resource/content/1/SYSC%204806%20%E2%80%93%20Optional%20Lab%20-%20PostgreSql.pdf) which is found as the optional lab on culearn.
Our JPA layer shouldn't be affected (there shouldn't be a need to change the entities and repository interfaces as long as this new database uses the same query syntax as H2 and is a relational DB).

**Comment by CameronRushton** [comment]
The instructions provided by the professor are profoundly useless if you don't develop on a macbook.

I've been able to swap over to a postgresql db by changing the project's application properties to match my local db. You can install the db following these steps on Windows 10:

Follow this tutorial to download and install postgresql and pgadmin to see the running db
1. https://www.guru99.com/download-install-postgresql.html
Download pgadmin: https://www.pgadmin.org/download/ only if for some reason it wasn't included in your postgresql installation.

During setup of postgresql:
I set my username = postgres
password = carleton
default uri is localhost:5432/postgres

The installer sucks. It'll never quit if you follow all the defaults and you'll reinstall stuff constantly. If you're at a window where you can choose what to install and it says postgresql is already installed in one of the submenus of choices, close the installer.

2. The tutorial says to look for pgadmin in your programs or using the windows search bar. Assuming you restarted your computer after installation and you booted up pgadmin and logged in to your db, you should be able to start the app with the following application properties, go to tools, sql query, and type `SELECT * FROM BUDDY_INFO;` and get a table.

```spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=carleton
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
```

![image](https://user-images.githubusercontent.com/32455969/75634249-fd10f800-5bd9-11ea-8235-7ccfac2762fc.png)

__________________________________________________________________________________________________________
I created a postgresql db attached to our heroku app using the heroku cli and running
`heroku addons:create heroku-postgresql:hobby-dev --app graduate-admission-system`
output

```
PS C:\Users\Shoyu> heroku addons:create heroku-postgresql:hobby-dev --app graduate-admission-system
Creating heroku-postgresql:hobby-dev on ⬢ graduate-admission-system... !
 !    Invalid credentials provided.
heroku: Press any key to open up the browser to login or q to exit:
Opening browser to https://cli-auth.heroku.com/auth/cli/browser/26d70d19-fdd3-43ff-8048-ae36639eb1c2
Logging in... done
Logged in as cameron.rushton@rogers.com
Creating heroku-postgresql:hobby-dev on ⬢ graduate-admission-system... free
Database has been created and is available
 ! This database is empty. If upgrading, you can transfer
 ! data from another database with pg:copy
Created postgresql-colorful-93517 as DATABASE_URL
Use heroku addons:docs heroku-postgresql to view documentation
```

Hopefully this should now work.

**Comment by CameronRushton** [comment]
Assuming this should be done in sprint 2 as the change isn't smooth since attempting to add the db to heroku failed on the first try.

**Comment by LukeANewton** [comment]
that makes sense. It would also be a good idea to talk on Wednesday about how this change will occur, so that everyone is on the same page
