### ISSUE TITLE
CORS blocking requests to back end

### ISSUE THREAD

**Issue by CameronRushton** [CameronRushton/Graduate-Admission-System#43]
CORS has been set up in a configuration bean but it appears to be allowing the wrong address only in production or presumably when the .war runs with the JRE manually. Perhaps adding the @ CrossOrigin annotation on every endpoint is required or theres a way to redo the global configuration that allows the right address. Allowing all origins is definitely not advised, but disabling it may be OK.

**Comment by LukeANewton** [comment]
what exactly do we need CORS for?

**Comment by CameronRushton** [comment]
This is something we can't disable since it's in all web browsers. Basically, when we serve an api, people want to request access to it from their own IP. When they do that using a browser or any other method, they'll first send an OPTIONS request and if the OPTIONS request comes back OK, it'll proceed with the ...let's say... GET request. This OPTIONS request is sent by the browser, so the user has no idea, and it will ask our api what is allowed to happen at the endpoint the user is trying to access. Things like... is my IP allowed? Am I allowed to do a GET on this endpoint? How long is the stuff you tell me good for, until I should ask again? Things like that. 

By not setting anything to do with CORS in our application, by default, nothing is sent back when the browser does an OPTIONS request, so the browser says, sorry user, I'm not sure if I'm allowed to do what you ask so I won't do it.
