### ISSUE TITLE
No alert when login unsuccessful

### ISSUE THREAD

**Issue by CameronRushton** [CameronRushton/Graduate-Admission-System#70]
When logging in, if the login fails, the button will say you're logged in, but nothing will happen. We should check to see if our promise was sent to the back end and if it wasn't or it returned some error, we need to communicate that to the user.
This is what the page looks like without the back end running and login button clicked.
![image](https://user-images.githubusercontent.com/32455969/76894371-67759980-6864-11ea-98d4-1650d764e0de.png)

**Comment by LukeANewton** [comment]
login functionalities are only about a third complete (at the time of writing this, I am waiting on Kevin's User repository). Once these are done, this may or may not still be an issue.
